<?php

namespace App\Http\Controllers;
use App\Http\Controllers\SBAuth\SBAuthController;
use Illuminate\Http\Request;

class InscriptionController extends SBAuthController
{
    //Constructeur
    public function __construct(){
    }

    public function registerHandler(Request $request)
    {
        return parent::register($request, '/users', '/'); // TODO: Change the autogenerated stub
    }



}
